# www.scons.org script files for COSMO computations using NWChem
#
# Use "nohup" to run from ssh and keep running after logout

import psutil
import time
import sys
import os
import shutil
import re


def checkIfRunning(processName):
	'''
	Check if there is any running process that contains the given name processName.
	'''
	#Iterate over the all the running process
	for proc in psutil.process_iter():
		try:
			# Check if process name contains the given name string.
			if processName.lower() in proc.name().lower():
				return True
		except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
			pass
	return False;

if checkIfRunning('nwchem'):
	print('NWchem is already running on this machine, exiting...')
#	sys.exit()

env = Environment()

env['ENV']['USER'] = os.environ['USER']
env['ENV']['HOME'] = os.environ['HOME']

# NWChem keys file stuff
keys_base = 'base-keys.txt'
file = open(keys_base,'r')
baseContents = file.read()
file.close()

def xyz_to_nw(target, source, env):
	xyz_file = source[0].rstr()
	nwchem_file = target[0].rstr()

	with open(xyz_file, "r") as f:
		lines = f.readlines()

	# Extract filename without extension for the title
	title = os.path.splitext(os.path.basename(xyz_file))[0]
	num_atoms = int(lines[0].strip())  # First line is the atom count
	atoms = [line.strip() for line in lines[2:num_atoms + 2]]  # Skip the second title/comment line

	# Check the charge
	charge = 0
	if title.endswith("+1"):
		charge = 1
	elif title.endswith("+2"):
		charge = 2
	elif title.endswith("+3"):
		charge = 3
	elif title.endswith("-1"):
		charge = -1
	elif title.endswith("-2"):
		charge = -2
	elif title.endswith("-3"):
		charge = -3

	# Generate the NWChem input file
	with open(nwchem_file, "w") as f:
		f.write(f"start {title}\n")
		if charge != 0:
			f.write(f"charge {charge}\n")
		f.write("geometry units angstrom noautoz\n")
		for atom in atoms:
			f.write(f"  {atom}\n")
		f.write("end\n")
        
		f.write(baseContents)

# Our custom builders
xyzToNw = Builder(action = xyz_to_nw, suffix = '.nw', single_source=True)
nwchemCosmo = Builder(action = os.environ['HOME'] + '/nwchem/bin/LINUX64/nwchem \"$SOURCE\" > \"${SOURCE.base}.out\"; ' +
                      'grep -q "failed" \"${SOURCE.base}.out\" && rm \"${SOURCE.base}.cosmo\"; ' + # delete the result if failed
					  'rm -f ' +
                      ' \"${SOURCE.base}\".gridpts.0 ' +
					  ' \"${SOURCE.base}\".aoints.0 ' +
					  ' \"${SOURCE.base}\".b' +
					  ' \"${SOURCE.base}\".b^-1' +
					  ' \"${SOURCE.base}\".c' +
					  ' \"${SOURCE.base}\".cosmo.xyz' +
					  ' \"${SOURCE.base}\".db' +
					  ' \"${SOURCE.base}\".p' +
					  ' \"${SOURCE.base}\".zmat' +
  					  ' \"${SOURCE.base}\".movecs'
					  ,suffix = '.cosmo', single_source=True)

env.Append(BUILDERS = {'XYZToNw' : xyzToNw})
env.Append(BUILDERS = {'NwToCosmo' : nwchemCosmo})

xyzfiles = Glob('*.xyz*')
files = []
files_big = []
files_p1 = []
files_m1 = []
files_m2 = []
for fi in xyzfiles :
	finame = os.path.splitext(fi.rstr())[0]
	if finame.endswith(".cosmo.xyz") :
		continue
	cosmofile = finame + '.cosmo'
	if os.path.exists(cosmofile):
		print('skipping ' + cosmofile)
		continue
	files.append(fi)

# Convert xyz files to nwchem input
nwFiles = env.XYZToNw(files)
cosmoFiles = env.NwToCosmo(nwFiles)
env.Depends(nwFiles, ['base-keys.txt'])

env.Default(cosmoFiles)

