# www.scons.org script files for COSMO computations using NWChem
#
# Use "nohup" to run from ssh and keep running after logout

import psutil
import time
import sys
import os
import os.path
import shutil
import re

# Set the nwchem executable and basis set folder
nwchem = os.environ['HOME'] + '/git/nwchem/bin/LINUX64/nwchem'
basis = os.environ['HOME'] + '/git/nwchem/src/basis/libraries'

if not os.path.isfile(nwchem):
	print('NWchem executable not found: ' + nwchem)
	sys.exit()

if not os.path.isdir(basis):
	print('NWchem basis set folder not found: ' + basis)
	sys.exit()

os.environ['NWCHEM_BASIS_LIBRARY'] = basis

import SCons.Errors

from rdkit import Chem
from rdkit.Chem import AllChem

env = Environment()

env['ENV']['USER'] = os.environ['USER']
env['ENV']['HOME'] = os.environ['HOME']

xyz_folder = "xyz/"
if not os.path.isdir(xyz_folder):
    os.mkdir(xyz_folder)

# NWChem keys file stuff
keys_base = 'base-keys.txt'
file = open(keys_base,'r')
baseContents = file.read()
file.close()

def mol_to_nw(target, source, env):
    mol_file = source[0].rstr()
    nwchem_file = target[0].rstr()

    # Load molecule from .mol file
    mol = Chem.MolFromMolFile(mol_file, removeHs=False)

    if mol is None:
        SCons.Errors.BuildError(node=target[0], errstr="Could not parse the .mol file.")
        return
    
    num_atoms = mol.GetNumAtoms()
    conf = mol.GetConformer()

    # Extract filename without extension for the title
    title = os.path.splitext(os.path.basename(mol_file))[0]

    # Check the charge
    charge = 0
    if title.endswith("+1"):
        charge = 1
    elif title.endswith("+2"):
        charge = 2
    elif title.endswith("+3"):
        charge = 3
    elif title.endswith("-1"):
        charge = -1
    elif title.endswith("-2"):
        charge = -2
    elif title.endswith("-3"):
        charge = -3

    # Generate the NWChem input file
    with open(nwchem_file, "w") as f:
        f.write(f"start {title}\n\n")
        if charge != 0:
            f.write(f"charge {charge}\n")
        f.write("geometry units angstrom noautoz\n")
        for atom in mol.GetAtoms():
            pos = conf.GetAtomPosition(atom.GetIdx())
            f.write(f"  {atom.GetSymbol()} {pos.x:.8f} {pos.y:.8f} {pos.z:.8f}\n")
        f.write("end\n\n")

        f.write(baseContents)

def out_to_xyz(target, source, env):
    out_file = source[0].rstr()
    xyz_file = xyz_folder + target[0].rstr()
    with open(out_file, 'r') as f:
        lines = f.readlines()
    
    # Find the line with "Optimization converged"
    opt_index = next((i for i, line in enumerate(lines) if "Optimization converged" in line), None)
    
    if opt_index is None:
        SCons.Errors.BuildError(node=target[0], errstr="Optimization not found in out file.")
        return
    
    # Extract energy (assuming it is a few lines below, starting with @)
    energy = None
    for i in range(opt_index, len(lines)):
        if lines[i].startswith('@'):
            elements = lines[i].split()
            energy = elements[2]
            break
    
    if energy is None:
        SCons.Errors.BuildError(node=target[0], errstr="Converged energy not found.")
        return
    
    # Extract geometry
    atom_lines = []
    for i in range(opt_index, len(lines)):
        if 'No.' in lines[i]:
            for j in range(i+2, len(lines)):
                elements = lines[j].split()
                if(len(elements) != 6):
                    break

                atom_lines.append(elements[1] +" "+ elements[3] +" "+ elements[4] +" "+ elements[5])
            break
    
    if not atom_lines:
        SCons.Errors.BuildError(node=target[0], errstr="No converged atomic coordinates found.")
        return
    
    # Write XYZ file
    with open(xyz_file, 'w') as f:
        f.write(f"{len(atom_lines)}\n")
        f.write(out_file + f" Energy: {energy}\n")
        for atom in atom_lines:
            f.write(atom + "\n")

# Our custom builders
molToNw = Builder(action = mol_to_nw, suffix = '.nw', single_source=True)
outToXyz = Builder(action = out_to_xyz, suffix = '.xyz', single_source=True)
# os.environ['HOME'] + '/nwchem/bin/LINUX64/nwchem
nwchemOut = Builder(action = 'mpirun -np 1 nwchem \"$SOURCE\" > \"${SOURCE.base}.out\"; ' +
                      'rm -f ' +
                      ' \"${SOURCE.base}\".gridpts.0 ' +
                      ' \"${SOURCE.base}\".aoints.0 ' +
                      ' \"${SOURCE.base}\".b' +
                      ' \"${SOURCE.base}\".b^-1' +
                      ' \"${SOURCE.base}\".c' +
                      ' \"${SOURCE.base}\".drv.hess' +
                      ' \"${SOURCE.base}\".db' +
                      ' \"${SOURCE.base}\".p' +
                      ' \"${SOURCE.base}\".zmat' +
                      ' \"${SOURCE.base}\".movecs'
                      ,suffix = '.out', single_source=True)

env.Append(BUILDERS = {'MolToNw' : molToNw})
env.Append(BUILDERS = {'NwToOut' : nwchemOut})
env.Append(BUILDERS = {'OutToXyz' : outToXyz})

molfiles = Glob('*.mol')
files = []
files_big = []
files_p1 = []
files_m1 = []
files_m2 = []
for fi in molfiles :
    finame = os.path.splitext(fi.rstr())[0]
    xyzfile = xyz_folder + finame + '.xyz'
    if os.path.exists(xyzfile):
        print('skipping ' + xyzfile)
        continue
    files.append(fi)

# Convert xyz files to nwchem input
nwFiles = env.MolToNw(files)
outFiles = env.NwToOut(nwFiles)
xyzFiles = env.OutToXyz(outFiles)

env.Depends(nwFiles, ['base-keys.txt'])

env.Default(xyzFiles)

